---
config:
  theme: neo
  layout: elk
  look: neo
---
classDiagram
    class Game {
        +currentRoom : Room
        +player : Player
        +difficulty
        +score : number
        +slowMeowHandler
        +nextRoom()
        +update()
        +draw()
        +handleInput()
    }
    class GameObject {
        <<abstract>>
        +pos : vector
        +vel : vector
        +widthHitBox : number
        +heightHitBox : number
        +widthModel : number
        +heightModel : number
        +isActive : boolean
        +update()
        +draw()
    }
    class Sprite {
        <<abstract>>
        +health : number
        +speed : number
        +direction : vector
        +activeEffects
        +takeDamage(amount)
        +draw()
    }
    class Player {
        +fireRate : number
        +lastShot : number
        +shoot()
        +move()
        +pickupItem()
        +handleInput()
    }
    class Mob {
        <<abstract>>
        +hitBoxWidth : number
        +hitBoxHeight : number
        +image
        +damage
        +moveTowardsPlayer()
    }
    class MeleeMob {
    }
    class RangedMob {
        +fire()
    }
    class BlinkMob {
        +blink()
    }
    class BuffMob {
        +handleIdleState()
        +moveToPosition()
    }
    class DashMob {
        +updateTrail()
        +prepareToDash()
        +dash()
    }
    class RapidFireMob {
        +rapidFireCooldown : number
        +rapidFireCooldownLimit : number
        +beginRapidFire()
        +handleRapidFire()
    }
    class Item {
        +image 
    }
    class Heart {
        +draw()
    }
    class Energy {
        +draw()
    }
    class Projectile {
        +damage
        +lifetime
        +update()
        +checkCollisions()
    }
    class Room {
        +width
        +height
        +mobs : Mob[]
        +projectiles : Projectile[]
        +items : Item[]
        +door : Door
        +tiles : Tile[][]
        +update()
        +draw()
        +addMob()
        +removMob()
    }
    class Door {
        +isOpen : boolean
        +direction
        +targetRoom
        +open()
        +close()
    }
    class Tile {
        +tileType
        +draw()
    }
    class RoomHandler {
        +currentRoom : Room
        +handleCollisions(GameObject)
        +updateProjectiles()
    }
    class RoomGenerator {
        +currentRoom : Room
        +initRoom()
        +addTraps()
        +addWalls()
        +addDoors()
    }
    class SlowMeowHandler {
        +currentRoom
        +applySlowMeow()
    }
    Game o-- Player
    Game *-- Room
    Room *-- Door
    Room *-- Mob
    Room *-- Item
    Room *-- Tile
    Room *-- Particle
    Room o-- SlowMeowHandler
    Room o-- RoomHandler
    Room o-- RoomGenerator
    Sprite <|-- Player
    Sprite <|-- Mob
    Sprite <|-- Item
    Mob <|-- MeleeMob
    Mob <|-- RangedMob
    Mob <|-- BlinkMob
    Mob <|-- BuffMob
    MeleeMob <|-- DashMob
    RangedMob <|-- RapidFireMob
    GameObject <|-- Tile
    GameObject <|-- Sprite
    GameObject <|-- Projectile
    GameObject <|-- Particle
    Item <|-- Heart
    Item <|-- Energy
